[package]
name = "gzpar"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
crc32fast = "1.4.2"
gzip-header = "1.0.0"
rayon = "1.10.0"
zlib-rs = "0.5.0"

[dev-dependencies]
flate2 = "1.1.1"
libz-rs-sys = "0.5.0"
